# Site settings
name: LiQingCode
email: 2222108065@stmail.ujs.edu.cn
author: LiQing
url: https://liqingcode.github.io/
resume_site: https://liqingcode.github.io/
github: https://github.com/LiQingCode/
baseurl: ""
description: Secret matrix
meta_description: 暂无
motto: My blo...g.
banner: 多写点儿有意思的东西，你说呢？

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: LiQingCode

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

